version: 2

jobs:
  build:
    docker:
      - image: "debian:buster"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++ build-essential git'
      - run:
          name: Install CMAKE 
          command: 'apt-get update && apt-get install -y cmake'
      - run:
          name: Installing other dependencies
          command: 'apt-get update && apt-get install -y libssl-dev zlib1g-dev curl wget'
      - run:
          name: Cloning D++
          command: 'git clone https://github.com/brainboxdotcc/DPP.git'
      - run:
          name: Creating D++ build files
          command: 'cmake  -HDPP -BDPP/build'
      - run:
          name: Building D++
          command: 'cmake --build DPP/build -j 8'
      - run:
          name: Installing D++
          command: 'cd DPP/build && make install'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build -j 8'

